const crypto = require("crypto"),
	  hash = crypto.createHash("sha512"),
	  https = require("https"),
	  qs = require("querystring");


// Data essentials.  
var key = "yjmEuMm4",
  	txnid = "1iuy383w72e", 
	amount = "600",
	firstname = "Rj",
	email = "rjwork333@gmail.com",
	phone = "8095478346";

// Post Options for Request.
var postOptions = {
	hostname: "secure.payu.in",
	path: "/_payment",
	method: "POST",
	headers: {
		"Content-Type": "application/x-form-urlencoded",		
	}
};

/**
 * Creates a hash out of the data.
 *
 * @param key {String} Merchant key.
 * @param txn {String} Random Txn id generated by us.
 * @param a {String} Amount to bill.
 * @param fname {Sring} Firstname of the customer.
 * @param em {String} Email Address of the customer.
 * @param ph {String} Phone.
 * @param h {Hex} Hash generated on basis of all details.
 */
var createHash = (function(key, txn, a, fname, em, ph) {
	var promise = new Promise((resolve, reject) => {
		hash.on("readable", () => {
			var createdHash = hash.read();
			if (createdHash !== "") resolve(createdHash.toString("hex").toLowerCase(), key, txnid, amount, firstname, email, phone);
		});	

		hash.write(key + "|" + txn + "|" + a + "|" + "None" + "|" + fname + "|" + em + "|||||||||||" + "9PthU9ldDm");
		hash.end();
	});
	return promise;
}).bind(null, key, txnid, amount, firstname, email, phone);


/**
 * Creates a postable string
 *
 * @param key {String} Merchant key.
 * @param txn {String} Random Txn id generated by us.
 * @param a {String} Amount to bill.
 * @param fname {Sring} Firstname of the customer.
 * @param em {String} Email Address of the customer.
 * @param ph {String} Phone.
 * @param h {Hex} Hash generated on basis of all details.
 */
var postReq = (function(key, txn, a, fname, em, ph, h) {
	var req = https.request(postOptions, (res) => {
		res.setEncoding("utf8");
		res.on("data", (chunk) => {
			console.log(chunk);
		});
		res.on("end", () => {
			console.log("No more Data.");		
		});
	});

	req.on("error", (e) => {
		console.log(`ERROR: ${e.message}`);
	});

	var dat = {};
	dat.key = key;
	dat.hash = h;
	dat.txnid = txn;
	dat.amount = a;
	dat.firstname = fname;
	dat.email = em;
	dat.phone = ph;
	dat.productinfo = "None";
	dat.service_provider = "payu_paisa";
	dat.surl = "http://www.facebook.com/success.html";
	dat.furl = "http://www.facebook.com/failure.html";

	req.end(qs.stringify(dat));	

}).bind(null, key, txnid, amount, firstname, email, phone);

createHash().then(postReq);